### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Device not found

### ISSUE THREAD

**Issue by congwing** [GrowthEase/GameSentry#10]
运行node index.js之后显示running on http://127.0.0.1:5000/   按官方指引这已经运行成功了，然后浏览器输入127.0.0.1:5000之后，就会出现下面报错，页面也打不开，一直加载。请问这是什么问题？
E:\GameSentry-main>node index.js
Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
(node:3944) UnhandledPromiseRejectionWarning: Error: Device not found
    at getMatchingDevice (E:\GameSentry-main\node_modules\frida\dist\index.js:109:15)
    at async E:\GameSentry-main\index.js:165:20
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3944) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3944) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by nszdhd1** [comment]
如果确认frida正常运行的话，可以试试其他frida版本

**Comment by congwing** [comment]
> 如果确认frida正常运行的话，可以试试其他frida版本

更换了指引里面的15.1.17版本的frida还是同样的报错

**Comment by nszdhd1** [comment]
UnhandledPromiseRejectionWarning: Error: Unable to communicate with remote frida-server; please ensure that major versions match and that the remote Frida has the feature you are trying to use
这个问题的提示的是frida-server的版本与电脑上的frida版本不一致，这个最好是检查一下frida-server的版本是否与电脑对应，确保frida-server正常运行
